repos:
  
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.14
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  
  - repo: local
    hooks:
      - id: type-check
        name: ty Type Check
        entry: uv run ty check
        types: [python]
        # always_run: true
      - id: pytest
        name: pytest
        entry: uv run pytest
        types: [python]
        # always_run: true